## Deliverable 3. Create a Travel Itinerary Map.

In [81]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import gkey

# Configure gmaps
gmaps.configure(api_key=gkey)

In [82]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("../Vacation_Search/WeatherPy_vacation.csv")
vacation_df.head()

City_ID         City Country  Max Temp Current Conditions      Lat  \
0        3      Rikitea      PF     78.03         light rain -23.1203   
1        8    Itabaiana      BR     86.00         few clouds -10.6850   
2        9       Atuona      PF     78.03          clear sky  -9.8000   
3       10       Vanimo      PG     80.02         light rain  -2.6741   
4       27  Niquelandia      BR     80.91      moderate rain -14.4739   

        Lng             Hotel Name  
0 -134.9692         Pension Maro'i  
1  -37.4253        Pousada Santana  
2 -139.0333            Villa Enata  
3  141.3028  Vahmoneh Lodge Vanimo  
4  -48.4597            Hotel Suinã

In [83]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Current Conditions}</dd>
<dt>Max Temperature</dt><dd>{Max Temp}</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [84]:
# 4a. Add a marker layer for each city to the map.
locations = vacation_df[["Lat", "Lng"]]

fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)

fig.add_layer(marker_layer)
# 4b. Display the figure
fig


Figure(layout=FigureLayout(height='420px'))

In [86]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[(vacation_df['City']== 'Santiago Del Estero')]
vacation_end = vacation_df.loc[(vacation_df['City']== 'Santiago Del Estero')]
vacation_stop1 = vacation_df.loc[(vacation_df['City']== 'Villa Carlos Paz')]
vacation_stop2 = vacation_df.loc[(vacation_df['City']== 'Santa Fe')] 
vacation_stop3 = vacation_df.loc[(vacation_df['City']== 'Reconquista')] 


In [87]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start[['Lat','Lng']].to_numpy()
end = vacation_end[['Lat','Lng']].to_numpy()
stop1 = vacation_stop1[['Lat','Lng']].to_numpy()
stop2 = vacation_stop2[['Lat','Lng']].to_numpy()
stop3 = vacation_stop3[['Lat','Lng']].to_numpy()
print(start)
print(end)
print(stop1)
print(stop2)
print(stop3)

[[-27.7951 -64.2615]]
[[-27.7951 -64.2615]]
[[-31.4241 -64.4978]]
[[-31.6333 -60.7   ]]
[[-29.15 -59.65]]


In [88]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
import gmaps
import gmaps.datasets
gmaps.configure(api_key=gkey)


fig = gmaps.figure()
itinerary= gmaps.directions_layer(start[0], end[0], waypoints=[stop1[0], stop2[0], stop3[0]],travel_mode='DRIVING')
fig.add_layer(itinerary)
fig

Figure(layout=FigureLayout(height='420px'))

In [89]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start,vacation_stop1,vacation_stop2,vacation_stop3]
                         ,ignore_index=True)
itinerary_df

City_ID                 City Country  Max Temp Current Conditions      Lat  \
0      419  Santiago Del Estero      AR     82.99         few clouds -27.7951   
1      157     Villa Carlos Paz      AR     81.00          clear sky -31.4241   
2      110             Santa Fe      AR     80.01          clear sky -31.6333   
3      401          Reconquista      AR     77.54    overcast clouds -29.1500   

       Lng          Hotel Name  
0 -64.2615        Hotel Urbano  
1 -64.4978         Monte Carlo  
2 -60.7000  Conquistador Hotel  
3 -59.6500         Grand Hotel

In [90]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Conditions} and {Max Temp}°F</dd>

</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [91]:
# 11a. Add a marker layer for each city to the map.
locations = itinerary_df[["Lat", "Lng"]]

fig = gmaps.figure()
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))